version: 0.2

phases:
  build:
    commands:
      - java -version
      - mvn install
      - mvn -X verify sonar:sonar

artifacts:
  files:
    - target/spring-boot-microservice-forex-service-0.0.1-SNAPSHOT.jar

  discard-paths: yes